export const SAVE_AUTHOR = 'SAVE_AUTHOR';
export const RETRIEVE_AUTHORS = 'RETRIEVE_AUTHORS';
export const UPDATE_AUTHOR = 'UPDATE_AUTHOR';
export const DELETE_AUTHOR = 'DELETE_AUTHOR';
export const DELETE_ALL_AUTHORS = 'DELETE_ALL_AUTHORS';
