export const SAVE_COURSE = 'SAVE_COURSE';
export const FETCH_COURSES = 'FETCH_COURSES';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const DELETE_ALL_COURSES = 'DELETE_ALL_COURSES';
